name: Update README with Latest Tweets

on:
  schedule:
    - cron: "0 0 */4 * *" # Runs every 4 days at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Latest Tweets
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          # Create temporary directory for JSON files
          mkdir -p tmp
      
          # Fetch latest tweets
          response=$(curl -s -X GET "https://api.twitter.com/2/users/1394170579503046660/tweets?max_results=5" \
            -H "Authorization: Bearer $TWITTER_BEARER_TOKEN")
      
          echo "$response" > tmp/user_and_tweets.json
      
          # Check if the response is empty
          if [ -z "$response" ]; then
            echo "Error: Empty response from Twitter API"
            exit 1
          fi
      
          # Check if the response contains an error
          if echo "$response" | jq -e '.errors' > /dev/null; then
            echo "Error: Twitter API returned an error:"
            echo "$response" | jq '.errors'
            exit 1
          fi
      
          # Check if the response data is null
          if echo "$response" | jq -e '.data == null' > /dev/null; then
            echo "Error: Invalid response from Twitter API"
            exit 1
          fi
      
          # Additional logging for debugging
          echo "Twitter API response: $response"
      
          # Extract tweets and format them into markdown
          echo "$response" | jq -r '.data[] | "* [\(.text)](https://twitter.com/waheed_hanzalah/status/\(.id))"' > tmp/latest_tweets.md
     
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -s tmp/latest_tweets.md ]; then
            # Use awk to replace the latest-tweets section in README.md
            awk '/<!-- latest-tweets-start -->/{p=1;print;print "";while(getline < "tmp/latest_tweets.md"){print}}/<!-- latest-tweets-end -->/{p=1}!p{print}' README.md > README.md.tmp && mv README.md.tmp README.md

            # To format the tweet spacing correctly.
            sed -i 's/\n/  <br>/g' tmp/latest_tweets.md

            # NEW: Debug - Print latest_tweets.md  (Correct Placement)
            cat tmp/latest_tweets.md

            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
            # Authenticate with PAT
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            
            git add README.md
            git commit -m "Update latest tweets"
            git push
          else
            echo "No updates to the README as there are no latest tweets."
          fi
