name: Update README with Latest Tweets

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every 24 hours at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Latest Tweets
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          # Create temporary directory for JSON files
          mkdir -p tmp

          # Fetch latest tweets
          response=$(curl -s -X GET "https://api.twitter.com/2/users/waheed_hanzalah/tweets?max_results=5" \
            -H "Authorization: Bearer $TWITTER_BEARER_TOKEN")

          echo "$response" > tmp/user_and_tweets.json

          # Check if the response contains an error
          if echo "$response" | jq -e '.errors' >/dev/null; then
            echo "Error: Twitter API returned an error:"
            echo "$response" | jq '.errors'
            exit 1
          fi

          # Extract tweets and format them into markdown
          echo "$response" | jq -r '.data[] | "* [\(.text)](https://twitter.com/waheed_hanzalah/status/\(.id))"' > tmp/latest_tweets.md

      - name: Update README
        run: |
          if [ -s tmp/latest_tweets.md ]; then
            # Use awk to replace the latest-tweets section in README.md
            awk '/<!-- latest-tweets-start -->/{p=1;print;print "";while(getline < "tmp/latest_tweets.md"){print}}/<!-- latest-tweets-end -->/{p=1}!p{print}' README.md > README.md.tmp && mv README.md.tmp README.md

            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
            git add README.md
            git commit -m "Update latest tweets"
            git push
          else
            echo "No updates to the README as there are no latest tweets."
          fi
